### ISSUE TITLE
A question about three types of iso

### ISSUE THREAD

**Issue by pkking** [Frodox/bitthinker.com#1]
As u mentioned at the post `There are three possible types of iso`,  but i think the last two types seem like to be the same.
These days, i tried fedora 25 livecd and ubuntu 16.04 desktop iso, both of them have ways of TRYING and INSTALL options, wondering what the differences between them.

**Comment by Frodox** [comment]
And did you try [CentOS 7 DVD](http://isoredirect.centos.org/centos/7/isos/x86_64/CentOS-7-x86_64-DVD-1611.iso) ? :) It allows to fall directly into installer (Anaconda). Also I can choose text mode or use kickstart (from [first boot-screen](https://svbtleusercontent.com/yjuannabkyhdw_small.png)).

Fedora vs Ubuntu Live boot into graphical env first, and only then I can click 
* 'Login Live System User', 
* 'please, install it on my PC!' 

I can't run installer without GUI (for example on server) or without booting into Live-Desktop.

**Comment by Frodox** [comment]
@pkking how are you? any more questions?

**Comment by pkking** [comment]
Our build system work very well recently :).
And i have already been transferred to another team which is not responsible for releng.
Feel free to close this issue :).
Thanks for your warm help!
